--SYS

SELECT * FROM DBA_UNUSED_COL_TABS;
--DBA로 시작하는 것은 관리자만 볼 수 있다.

SELECT COUNT(*) FROM DICTIONARY; --내가 쓸 수 있는 DICTIONARY 개수



--DCL(GRANT,REVOKE)
--GRANT: USER나 OBJECT에 권한을 부여할 때 사용
--REVOKE: USER나 OBJECT에 권한을 회수할 때 사용

CREATE USER TEST
IDENTIFIED BY TEST
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 1M ON USERS;

CREATE USER INSA
IDENTIFIED BY INSA
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 1M ON USERS;

SELECT * FROM DBA_USERS;

SELECT * FROM V$SESSION
WHERE USERNAME IS NOT NULL;



--권한의 종류
SELECT * FROM SYSTEM_PRIVILEGE_MAP; --줄 수 있는 권한의 종류

--SYSTEM 권한 : DATABASE의 OBJECT들을 생성(CREATE), 수정(ALTER), 삭제(DROP)할 수 있는 권한	
--				DBA권한을 가진 사람이 일반 USERS한테 준다.
--OBJECT 권한 : USER가 만든 OBJECT를 조작(INSERT, UPDATE, DELETE, SELECT)
--OBJECT : TABLE, ROLE, SEQUENCE, VIEW, SYSNONYM

--모든 사람들한테 줄 때에는 PUBLIC을 쓴다.
GRANT CREATE USER TO KIM;

GRANT CREATE SESSION,CREATE SYNONYM TO TEST;


--ROLE(역할)
--CONNECT, RESOURCE

SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE IN('CONNECT','RESOURCE','MANAGER')
ORDER BY ROLE;
--일반사용자가 RESOURCE를 받았기 때문에 테이블을 만들 수 있다.


CREATE ROLE MANAGER;

SELECT * FROM DBA_ROLES;

GRANT CREATE SESSION,CREATE TABLE,CREATE USER TO MANAGER;
--SYSTEM권한을 넣었다. CREATE로 시작하는 것은 SYSTEM 권한

GRANT MANAGER TO INSA;

REVOKE MANAGER FROM INSA;
--INSA에게서 MANAGER라는 그릇을 뺏어온 것이다.



GRANT CREATE ROLE TO KIM;

GRANT CREATE VIEW TO KIM;











